title: ESP32 õppematerjal
description: Eestikeelne õppematerjal ESP32 asjade interneti kursusele
theme: just-the-docs

url: https://karlthefish.github.io/esp32-oppematerjal

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/KarlTheFish/esp32-oppematerjal

color_scheme: dark

callouts:
  info:
    title: Lisainfo
    color: blue
  important:
    title: Tähtis!
    color: red
  todo:
    title: TODO!!!
    color: yellow
